# Generated by Django 5.2.5 on 2026-09-04 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('self_contain', 'Self Contain'), ('single_room', 'Single Room'), ('shared_apartment', 'Shared Apartment'), ('room_parlour', 'Room & Parlour'), ('apartment', 'Apartment')], max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(default='Gidan Kwano, Minna', max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('starlink', models.BooleanField(default=False)),
                ('private_transformer', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('solar_power', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('water_heater', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('borehole', models.BooleanField(default=False)),
                ('network_coverage', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='properties/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
