# Generated by Django 5.2.5 on 2026-09-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_propertyimage_propertyvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
