# Generated by Django 5.2.5 on 2026-09-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_remove_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('gk_main_gate', 'Gidan Kwano - Main Gate Area'), ('gk_market_hub', 'Gidan Kwano - Market / Commercial Hub'), ('gk_residential_west', 'Gidan Kwano - Residential West'), ('gk_express_axis', 'Gidan Kwano - Express Axis'), ('dama_north', 'Dama - North Campus Axis'), ('dama_central', 'Dama - Central Village'), ('dama_south', 'Dama - South Extension'), ('gm_main_road', 'Gidan Mangoro - Main Road Corridor'), ('gm_interior', 'Gidan Mangoro - Interior Lodges')], default='gk_main_gate', max_length=30)),
                ('latitude', models.FloatField(default=9.584)),
                ('longitude', models.FloatField(default=6.45)),
                ('landmark', models.CharField(blank=True, help_text='e.g. Opposite Central Mosque, Near GK Shuttle Park', max_length=150)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_details', to='realestate.property')),
            ],
        ),
    ]
