# Generated by Django 5.2.5 on 2026-09-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_propertylocation_distance_to_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylocation',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
