# Generated by Django 5.2.5 on 2026-09-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_propertylocation_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertylocation',
            name='zone',
            field=models.CharField(choices=[('gk_main_gate', 'Gidan Kwano - Front Of School'), ('gk_express_south_west', 'Gidan Kwano - Munchbox'), ('gk_market_hub', 'Gidan Kwano - MM Castle'), ('gk_residential_west', 'Gidan Kwano - RCF'), ('gk_residential_east', 'Gidan Kwano - Talba Road'), ('gk_express_south_south', 'Gidan Kwano - Sambisa Axis'), ('gk_express_south', 'Gidan Kwano - Living Faith'), ('gk_express_north', 'Gidan Kwano - RGGC Chapel'), ('gk_express_south_west', 'Gidan Kwano - RGGC Chapel'), ('dama_north', 'Dama - North Campus Axis'), ('dama_central', 'Dama - Central Village'), ('dama_south', 'Dama - South Extension'), ('gm_main_road', 'Gidan Mangoro - Main Road Corridor'), ('gm_interior', 'Gidan Mangoro - Interior Lodges'), ('gm_east', 'Gidan Mangoro - East Axis')], default='gk_main_gate', max_length=50),
        ),
    ]
