# Generated by Django 5.2.5 on 2026-09-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_property_phone_number_property_website_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='website',
            new_name='linke',
        ),
    ]
