# Generated by Django 5.2.5 on 2026-09-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_rename_website_property_linke'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='linke',
            new_name='link',
        ),
    ]
